In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [3]:

# Load the dataset using its absolute file path
file_path = "/home/richard/Netflix_Fresh/data/raw/Dataset.csv"

df = pd.read_csv(file_path)

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

df.head()

Number of rows: 8790
Number of columns: 10

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [4]:

# Display column names and data types
print("Dataset information:")
df.info()

# Check the dataset dimensions
print("\nDataset shape:", df.shape)

# Display statistical summary
df.describe(include="all").T

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   object
 1   type          8790 non-null   object
 2   title         8790 non-null   object
 3   director      8790 non-null   object
 4   country       8790 non-null   object
 5   date_added    8790 non-null   object
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   object
 8   duration      8790 non-null   object
 9   listed_in     8790 non-null   object
dtypes: int64(1), object(9)
memory usage: 686.8+ KB

Dataset shape: (8790, 10)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
show_id,8790,8790,s1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
type,8790,2,Movie,6126,NaN,NaN,NaN,NaN,NaN,NaN,NaN
title,8790,8787,9-Feb,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
director,8790,4528,Not Given,2588,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country,8790,86,United States,3240,NaN,NaN,NaN,NaN,NaN,NaN,NaN
date_added,8790,1713,1/1/2020,110,NaN,NaN,NaN,NaN,NaN,NaN,NaN
release_year,8790.0,NaN,NaN,NaN,2014.183163,8.825466,1925.0,2013.0,2017.0,2019.0,2021.0
rating,8790,14,TV-MA,3205,NaN,NaN,NaN,NaN,NaN,NaN,NaN
duration,8790,220,1 Season,1791,NaN,NaN,NaN,NaN,NaN,NaN,NaN
listed_in,8790,513,"Dramas, International Movies",362,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:

# Count missing values in each column
print("Missing values per column:")
print(df.isnull().sum())

# Count fully duplicated rows
print("\nNumber of duplicate rows:", df.duplicated().sum())

# Check repeated titles
print("\nNumber of repeated title entries:", df["title"].duplicated().sum())

# Inspect placeholder values
print("\n'Not Given' counts:")
for column in ["director", "country", "rating"]:
    print(f"{column}: {(df[column] == 'Not Given').sum()}")

Missing values per column:
show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

Number of duplicate rows: 0

Number of repeated title entries: 3

'Not Given' counts:
director: 2588
country: 287
rating: 0

In [6]:

# Display titles that appear more than once
repeated_titles = df[df["title"].duplicated(keep=False)].sort_values("title")

repeated_titles[["show_id", "title", "type", "release_year", "country"]]

     show_id   title     type  release_year   country
2925   s3963  15-Aug    Movie          2019     India
4261   s5967  15-Aug    Movie          2019     India
3285   s4523  22-Jul    Movie          2018    Norway
4260   s5966  22-Jul    Movie          2018    Norway
393    s3997   9-Feb  TV Show          2018  Pakistan
537    s5965   9-Feb  TV Show          2018  Pakistan

In [7]:

# Check the original column names
print("Column names:")
print(df.columns.tolist())

# Display selected records without changing the dataset
display(df.iloc[[2925, 4261, 3285, 4260, 393, 537]])

# Check the first few records
display(df.head())

Column names:
['show_id', 'type', 'title', 'director', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in']

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
2925,s3963,Movie,15-Aug,Swapnaneel Jayakar,India,3/29/2019,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"
4261,s5967,Movie,15-Aug,Swapnaneel Jayakar,India,3/29/2019,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"
3285,s4523,Movie,22-Jul,Paul Greengrass,Norway,10/10/2018,2018,R,144 min,"Dramas, Thrillers"
4260,s5966,Movie,22-Jul,Paul Greengrass,Norway,10/10/2018,2018,R,144 min,"Dramas, Thrillers"
393,s3997,TV Show,9-Feb,Not Given,Pakistan,3/20/2019,2018,TV-14,1 Season,"International TV Shows, TV Dramas"
537,s5965,TV Show,9-Feb,Not Given,Pakistan,3/20/2019,2018,TV-14,1 Season,"International TV Shows, TV Dramas"

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [8]:

# Compare duplicate titles, excluding the unique show_id
comparison_columns = [
    "type", "title", "director", "country", "date_added",
    "release_year", "rating", "duration", "listed_in"
]

repeated_titles = df[df["title"].duplicated(keep=False)]

for title, group in repeated_titles.groupby("title"):
    print(f"\nTitle: {title}")
    display(group[comparison_columns])
    print(
        "All other columns identical:",
        group[comparison_columns].drop_duplicates().shape[0] == 1
    )

Title: 15-Aug

,type,title,director,country,date_added,release_year,rating,duration,listed_in
2925,Movie,15-Aug,Swapnaneel Jayakar,India,3/29/2019,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"
4261,Movie,15-Aug,Swapnaneel Jayakar,India,3/29/2019,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"

All other columns identical: True

Title: 22-Jul

,type,title,director,country,date_added,release_year,rating,duration,listed_in
3285,Movie,22-Jul,Paul Greengrass,Norway,10/10/2018,2018,R,144 min,"Dramas, Thrillers"
4260,Movie,22-Jul,Paul Greengrass,Norway,10/10/2018,2018,R,144 min,"Dramas, Thrillers"

All other columns identical: True

Title: 9-Feb

,type,title,director,country,date_added,release_year,rating,duration,listed_in
393,TV Show,9-Feb,Not Given,Pakistan,3/20/2019,2018,TV-14,1 Season,"International TV Shows, TV Dramas"
537,TV Show,9-Feb,Not Given,Pakistan,3/20/2019,2018,TV-14,1 Season,"International TV Shows, TV Dramas"

All other columns identical: True

In [9]:

# Record the number of rows before cleaning
rows_before = len(df)

# Remove exact duplicates across all columns except the unique show_id
df = df.drop_duplicates(subset=[
    "type", "title", "director", "country", "date_added",
    "release_year", "rating", "duration", "listed_in"
])

# Check the result
rows_after = len(df)

print("Rows before cleaning:", rows_before)
print("Rows after cleaning:", rows_after)
print("Duplicate records removed:", rows_before - rows_after)

Rows before cleaning: 8790
Rows after cleaning: 8787
Duplicate records removed: 3

In [10]:

# Standardize whitespace in text columns
text_columns = df.select_dtypes(include="object").columns

for column in text_columns:
    df[column] = df[column].str.strip()

# Replace placeholder values with actual missing values
df[["director", "country"]] = df[["director", "country"]].replace(
    "Not Given", np.nan
)

# Check the results
print("Missing values after standardization:")
print(df.isnull().sum())

print("\nSample standardized records:")
display(df.head())

Missing values after standardization:
show_id            0
type               0
title              0
director        2587
country          287
date_added         0
release_year       0
rating             0
duration           0
listed_in          0
dtype: int64

Sample standardized records:

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [11]:

# Standardize content type and rating labels
df["type"] = df["type"].str.strip().str.title()
df["rating"] = df["rating"].str.strip().str.upper()

# Check unique values
print("Content types:")
print(df["type"].value_counts())

print("\nRating categories:")
print(sorted(df["rating"].dropna().unique()))

# Check for missing ratings
print("\nMissing ratings:", df["rating"].isna().sum())

Content types:
type
Movie      6124
Tv Show    2663
Name: count, dtype: int64

Rating categories:
['G', 'NC-17', 'NR', 'PG', 'PG-13', 'R', 'TV-14', 'TV-G', 'TV-MA', 'TV-PG', 'TV-Y', 'TV-Y7', 'TV-Y7-FV', 'UR']

Missing ratings: 0

In [12]:

# Restore the standard Netflix content-type labels
df["type"] = df["type"].replace({
    "Tv Show": "TV Show",
    "Movie": "Movie"
})

# Verify the final labels and counts
print(df["type"].value_counts())

type
Movie      6124
TV Show    2663
Name: count, dtype: int64

In [13]:

# Convert date_added from text to datetime
df["date_added"] = pd.to_datetime(
    df["date_added"],
    format="%m/%d/%Y",
    errors="coerce"
)

# Check the results
print("Data type:", df["date_added"].dtype)
print("Missing dates:", df["date_added"].isna().sum())

print("\nEarliest date added:", df["date_added"].min())
print("Latest date added:", df["date_added"].max())

display(df[["title", "date_added"]].head())

Data type: datetime64[ns]
Missing dates: 0

Earliest date added: 2008-01-01 00:00:00
Latest date added: 2021-09-25 00:00:00

                              title date_added
0              Dick Johnson Is Dead 2021-09-25
1                         Ganglands 2021-09-24
2                     Midnight Mass 2021-09-24
3  Confessions of an Invisible Girl 2021-09-22
4                           Sankofa 2021-09-24

In [14]:

# Identify titles that look like abbreviated dates
date_like_titles = df[
    df["title"].str.fullmatch(
        r"\d{1,2}-[A-Za-z]{3}",
        na=False
    )
]

print("Number of date-like titles:", len(date_like_titles))
display(
    date_like_titles[
        ["show_id", "title", "type", "release_year", "country"]
    ]
)

Number of date-like titles: 4

     show_id   title     type  release_year   country
393    s3997   9-Feb  TV Show          2018  Pakistan
2925   s3963  15-Aug    Movie          2019     India
3285   s4523  22-Jul    Movie          2018    Norway
4259   s5964   1-Oct    Movie          2014   Nigeria

In [15]:

# Final data-quality checks
print("Final dataset shape:", df.shape)

print("\nDuplicate rows:", df.duplicated().sum())

print("\nMissing values per column:")
print(df.isna().sum())

print("\nUnique content types:")
print(df["type"].unique())

print("\nUnique show IDs:", df["show_id"].nunique())

print("\nDate-like titles retained:", len(date_like_titles))

Final dataset shape: (8787, 10)

Duplicate rows: 0

Missing values per column:
show_id            0
type               0
title              0
director        2587
country          287
date_added         0
release_year       0
rating             0
duration           0
listed_in          0
dtype: int64

Unique content types:
['Movie' 'TV Show']

Unique show IDs: 8787

Date-like titles retained: 4

In [16]:

# Save the cleaned dataset
output_path = "/home/richard/Netflix_Fresh/data/cleaned/netflix_cleaned.csv"

df.to_csv(output_path, index=False)

print("Cleaned dataset saved successfully!")
print("File location:", output_path)
print("Rows saved:", len(df))

Cleaned dataset saved successfully!
File location: /home/richard/Netflix_Fresh/data/cleaned/netflix_cleaned.csv
Rows saved: 8787

In [17]:

# Reload the saved cleaned dataset
df_check = pd.read_csv(output_path)

print("File exists and is readable.")
print("Verified shape:", df_check.shape)
print("Columns:", df_check.columns.tolist())

File exists and is readable.
Verified shape: (8787, 10)
Columns: ['show_id', 'type', 'title', 'director', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in']